import os
# 获取当前文件目录
print('--------- 获取当前程序的执行目录路径/一般是当前程序所在的目录路径')
print(os.getcwd())
f = os.path.abspath(r'data\abc.txt')
print('--------- 是否为完整路径表示')
print(os.path.isabs(f))
print('--------- 所在父目录和当前目录名或数据文件名本身')
print(os.path.split(f))
print('--------- 如果是数据文件，以.扩展名拆分为两部分')
print(os.path.splitext(f))
print('--------- 所在父目录路径')
print(os.path.dirname(f))
print('--------- 当前目录名或数据文件名本身')
print(os.path.basename(f))
print('--------- 是否为数据文件')
print(os.path.isfile(f))
print('--------- 是否为目录')
print(os.path.isdir(f))
print('--------- 目录所表示的目录或出具文件是否存在')
print(os.path.exists(f))
print('--------- 数据文件大小,目录则为0')
print(os.path.getsize(f))
